services:
  postgres:
    image: postgres:16
    container_name: sentinel-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - sentinel-network

  sentinel-back:
    build: .
    container_name: sentinel-back
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/sentinel?schema=public
      - PORT=3000
    depends_on:
      - postgres
    networks:
      - sentinel-network

volumes:
  pg_data:

networks:
  sentinel-network:
    driver: bridge
