services:
  postgres:
    image: postgres:16
    container_name: sentinel-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - sentinel-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  sentinel-back:
    build: .
    container_name: sentinel-back
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/sentinel?schema=public
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sentinel-network

  test-runner:
    build: .
    container_name: sentinel-tests
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/sentinel?schema=public
      - PORT=3000
      - TEST_BASE_URL=http://sentinel-back:3000/api
    depends_on:
      sentinel-back:
        condition: service_started
    command: >
      sh -c "sleep 10 && npx ts-node test/login/test-change-password.ts"
    networks:
      - sentinel-network

volumes:
  pg_data:

networks:
  sentinel-network:
    driver: bridge
